#!/usr/bin/env bash

# pgrep -x sxhkd > /dev/null || sxhkd &
# nm-applet &
# blueman-applet &
picom &
fcitx5 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# libinput-gestures-setup start &
greenclip daemon &
xmodmap ~/.Xmodmap &
