#!/bin/sh

~/.config/bspwm/autostart

bspc monitor -d HOME WEB CODE NOTE MISC

bspc config border_width 2
bspc config window_gap   8

bspc config focus_follows_pointer false

bspc config split_ratio        0.5
bspc config borderless_monocle true
bspc config gapless_monocle    true

bspc config focused_border_color  "#242B38"
bspc config normal_border_color   "#3E4452"
bspc config active_border_color   "#E2E8F0"
bspc config presel_feedback_color "#61AFEF"

~/.config/bspwm/windows
