#!/bin/sh

~/.config/bspwm/autostart

bspc monitor -d HOME WEB CODE MISC

bspc config border_width         2
bspc config window_gap           8

bspc config focus_follows_pointer false

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#364e6a"
bspc config normal_border_color "#13171e"
bspc config active_border_color "#FFFFFF"
bspc config presel_feedback_color "#98C379"

~/.config/bspwm/windows
