#!/bin/bash

TOKEN=VAqZgLrNwWIMKaM7vbFztWZlTFO47rqx
API_URL=https://sm.ms/api/v2/upload

function upload_img() {
    filename=$(zenity --file-selection --filename ~/Pictures/Screenshots/)
    response=$(curl -s -H "Authorization:$TOKEN" -F smfile=@$filename $API_URL)
    echo $response
    code=$(echo $response | jq -r .code)
    if [ "$code" = "success" ]; then
        name=$(echo $response | jq -r .data.filename)
        img_url=$(echo $response | jq -r .data.url)
        echo $img_url | xclip -selection clipboard
        notify-send "$name uploaded successfully! The url to the image has been copied to your clipboard."
    else
        notify-send -u critical "Failed to upload the image!"
    fi
}

upload_img
